project_id = "lrvisxodjsubifwyfkjr"

[functions.transcribe-sermon]
verify_jwt = false

[functions.export-sermon]
verify_jwt = true

[functions.evaluate-sermon]
verify_jwt = true

[functions.combine-audio]
verify_jwt = true

[functions.summarize-comments]
verify_jwt = true

[functions.count-scripture-refs]
verify_jwt = false

[functions.generate-sermon-report]
verify_jwt = true

[functions.transcribe-audio-comment]
verify_jwt = true

[functions.download-audio-url]
verify_jwt = false

[functions.download-podcast-url]
verify_jwt = false

[functions.download-youtube-audio]
verify_jwt = false

[functions.flag-confusing-phrases]
verify_jwt = false
